###############################################################################
# Quarkus configurations
###############################################################################
quarkus:
  http:
    port: 8080

  ###############################################################################
  # Datasource configuration
  ###############################################################################
  datasource:
    db-kind: postgresql
    username: hibernate
    password: hibernate
    jdbc:
      url: jdbc:postgresql://localhost:5432/hibernate_db

  ###############################################################################
  # Hibernate ORM Configuration
  ###############################################################################
  hibernate-orm:
    database:
      generation: drop-and-create