version: '3.8'

services:

  #############################################################################
  # Postgres
  #############################################################################
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hibernate
      POSTGRES_PASSWORD: hibernate
      POSTGRES_DB: hibernate_db